export const beneficiaryCountries = {
  response: {
    status: true,
    errorCode: 0,
    errorDescription: null,
    responseDto: [
      {
        referenceCountryCode: "AF",
        isActive: true,
        bankCodeLabel: "Bank Code",
        countryId: 22,
        countryName: "Afghanistan",
      },
      {
        referenceCountryCode: "AD",
        isActive: true,
        bankCodeLabel: "Bank Code",
        swiftCodeLabel: "Swift Code",
        countryId: 28,
        countryName: "Andorra",
      },
      {
        referenceCountryCode: "AU",
        isActive: true,
        bankCodeLabel: "Bank Code",
        swiftCodeLabel: "Swift Code",
        countryId: 26,
        countryName: "Australia",
      },
      {
        referenceCountryCode: "AT",
        isActive: true,
        bankCodeLabel: "Bank Code",
        swiftCodeLabel: "Swift Code",
        countryId: 29,
        countryName: "Austria",
      },
      {
        referenceCountryCode: "PT",
        isActive: true,
        bankCodeLabel: "Bank Code",
        swiftCodeLabel: "Swift Code",
        countryId: 30,
        countryName: "Azores",
      },
      {
        referenceCountryCode: "BD",
        isActive: true,
        bankCodeLabel: "Bank Code",
        countryId: 20,
        countryName: "Bangladesh",
      },
      {
        referenceCountryCode: "BE",
        isActive: true,
        countryId: 19,
        countryName: "Belgium",
      },
      {
        referenceCountryCode: "BG",
        isActive: true,
        bankCodeLabel: "Bank Code",
        swiftCodeLabel: "Swift Code",
        countryId: 31,
        countryName: "Bulgaria",
      },
      {
        referenceCountryCode: "CA",
        isActive: true,
        bankCodeLabel: "Transit Number",
        swiftCodeLabel: "Swift Code",
        countryId: 7,
        countryName: "Canada",
      },
      {
        referenceCountryCode: "ES",
        isActive: true,
        bankCodeLabel: "Bank Code",
        swiftCodeLabel: "Swift Code",
        countryId: 32,
        countryName: "Canary Islands",
      },
      {
        referenceCountryCode: "CN",
        isActive: true,
        bankCodeLabel: "CNAPS Code",
        swiftCodeLabel: "Swift Code",
        countryId: 8,
        countryName: "China",
      },
      {
        referenceCountryCode: "CD",
        isActive: true,
        bankCodeLabel: "Bank Code",
        countryId: 14,
        countryName: "Congo",
      },
      {
        referenceCountryCode: "HR",
        isActive: true,
        bankCodeLabel: "Bank Code",
        swiftCodeLabel: "Swift Code",
        countryId: 33,
        countryName: "Croatia",
      },
      {
        referenceCountryCode: "CY",
        isActive: true,
        bankCodeLabel: "Bank Code",
        swiftCodeLabel: "Swift Code",
        countryId: 34,
        countryName: "Cyprus",
      },
      {
        referenceCountryCode: "CZ",
        isActive: true,
        bankCodeLabel: "Bank Code",
        swiftCodeLabel: "Swift Code",
        countryId: 35,
        countryName: "Czech Republic",
      },
      {
        referenceCountryCode: "DK",
        isActive: true,
        bankCodeLabel: "Bank Code",
        swiftCodeLabel: "Swift Code",
        countryId: 36,
        countryName: "Denmark",
      },
      {
        referenceCountryCode: "EE",
        isActive: true,
        countryId: 17,
        countryName: "Estonia",
      },
      {
        referenceCountryCode: "EU",
        isActive: true,
        countryId: 24,
        countryName: "Europe",
      },
      {
        referenceCountryCode: "FI",
        isActive: true,
        bankCodeLabel: "Bank Code",
        swiftCodeLabel: "Swift Code",
        countryId: 37,
        countryName: "Finland",
      },
      {
        referenceCountryCode: "FR",
        isActive: true,
        countryId: 18,
        countryName: "France",
      },
      {
        referenceCountryCode: "GF",
        isActive: true,
        bankCodeLabel: "Bank Code",
        swiftCodeLabel: "Swift Code",
        countryId: 38,
        countryName: "French Guiana",
      },
      {
        referenceCountryCode: "DE",
        isActive: true,
        bankCodeLabel: "Bank Code",
        swiftCodeLabel: "Swift Code",
        countryId: 39,
        countryName: "Germany",
      },
      {
        referenceCountryCode: "GH",
        isActive: true,
        bankCodeLabel: "Bank Code",
        countryId: 15,
        countryName: "Ghana",
      },
      {
        referenceCountryCode: "GI",
        isActive: true,
        bankCodeLabel: "Bank Code",
        swiftCodeLabel: "Swift Code",
        countryId: 40,
        countryName: "Gibraltar",
      },
      {
        referenceCountryCode: "GR",
        isActive: true,
        bankCodeLabel: "Bank Code",
        countryId: 23,
        countryName: "Greece",
      },
      {
        referenceCountryCode: "GP",
        isActive: true,
        bankCodeLabel: "Bank Code",
        swiftCodeLabel: "Swift Code",
        countryId: 41,
        countryName: "Guadeloupe",
      },
      {
        referenceCountryCode: "GG",
        isActive: true,
        bankCodeLabel: "Bank Code",
        swiftCodeLabel: "Swift Code",
        countryId: 42,
        countryName: "Guernsey",
      },
      {
        referenceCountryCode: "HU",
        isActive: true,
        bankCodeLabel: "Bank Code",
        swiftCodeLabel: "Swift Code",
        countryId: 43,
        countryName: "Hungary",
      },
      {
        referenceCountryCode: "IS",
        isActive: true,
        bankCodeLabel: "Bank Code",
        swiftCodeLabel: "Swift Code",
        countryId: 44,
        countryName: "Iceland",
      },
      {
        referenceCountryCode: "IN",
        isActive: true,
        bankCodeLabel: "IFSC",
        swiftCodeLabel: "Swift Code",
        countryId: 2,
        countryName: "India",
      },
      {
        referenceCountryCode: "IE",
        isActive: true,
        bankCodeLabel: "Bank Code",
        swiftCodeLabel: "Swift Code",
        countryId: 45,
        countryName: "Ireland",
      },
      {
        referenceCountryCode: "IM",
        isActive: true,
        bankCodeLabel: "Bank Code",
        swiftCodeLabel: "Swift Code",
        countryId: 46,
        countryName: "Isle of Man",
      },
      {
        referenceCountryCode: "IT",
        isActive: true,
        bankCodeLabel: "Bank Code",
        swiftCodeLabel: "Swift Code",
        countryId: 47,
        countryName: "Italy",
      },
      {
        referenceCountryCode: "JE",
        isActive: true,
        bankCodeLabel: "Bank Code",
        swiftCodeLabel: "Swift Code",
        countryId: 48,
        countryName: "Jersey",
      },
      {
        referenceCountryCode: "KE",
        isActive: true,
        bankCodeLabel: "Bank Code",
        countryId: 12,
        countryName: "Kenya",
      },
      {
        referenceCountryCode: "LV",
        isActive: true,
        bankCodeLabel: "Bank Code",
        swiftCodeLabel: "Swift Code",
        countryId: 49,
        countryName: "Latvia",
      },
      {
        referenceCountryCode: "LI",
        isActive: true,
        bankCodeLabel: "Bank Code",
        swiftCodeLabel: "Swift Code",
        countryId: 50,
        countryName: "Liechtenstein",
      },
      {
        referenceCountryCode: "LT",
        isActive: true,
        bankCodeLabel: "Bank Code",
        swiftCodeLabel: "Swift Code",
        countryId: 51,
        countryName: "Lithuania",
      },
      {
        referenceCountryCode: "LU",
        isActive: true,
        bankCodeLabel: "Bank Code",
        swiftCodeLabel: "Swift Code",
        countryId: 52,
        countryName: "Luxembourg",
      },
      {
        referenceCountryCode: "PT",
        isActive: true,
        bankCodeLabel: "Bank Code",
        swiftCodeLabel: "Swift Code",
        countryId: 53,
        countryName: "Madeira",
      },
      {
        referenceCountryCode: "MT",
        isActive: true,
        bankCodeLabel: "Bank Code",
        swiftCodeLabel: "Swift Code",
        countryId: 54,
        countryName: "Malta",
      },
      {
        referenceCountryCode: "MQ",
        isActive: true,
        bankCodeLabel: "Bank Code",
        swiftCodeLabel: "Swift Code",
        countryId: 55,
        countryName: "Martinique",
      },
      {
        referenceCountryCode: "YT",
        isActive: true,
        bankCodeLabel: "Bank Code",
        swiftCodeLabel: "Swift Code",
        countryId: 56,
        countryName: "Mayotte",
      },
      {
        referenceCountryCode: "MC",
        isActive: true,
        bankCodeLabel: "Bank Code",
        swiftCodeLabel: "Swift Code",
        countryId: 57,
        countryName: "Monaco",
      },
      {
        referenceCountryCode: "NP",
        isActive: true,
        bankCodeLabel: "Bank Code",
        countryId: 13,
        countryName: "Nepal",
      },
      {
        referenceCountryCode: "NL",
        isActive: true,
        bankCodeLabel: "Bank Code",
        swiftCodeLabel: "Swift Code",
        countryId: 58,
        countryName: "Netherlands",
      },
      {
        referenceCountryCode: "NG",
        isActive: true,
        bankCodeLabel: "Bank Code",
        countryId: 16,
        countryName: "Nigeria",
      },
      {
        referenceCountryCode: "NO",
        isActive: true,
        bankCodeLabel: "Bank Code",
        swiftCodeLabel: "Swift Code",
        countryId: 59,
        countryName: "Norway",
      },
      {
        referenceCountryCode: "PH",
        isActive: true,
        bankCodeLabel: "Bank Code",
        swiftCodeLabel: "Swift Code",
        countryId: 5,
        countryName: "Philipines",
      },
      {
        referenceCountryCode: "PL",
        isActive: true,
        bankCodeLabel: "Bank Code",
        swiftCodeLabel: "Swift Code",
        countryId: 60,
        countryName: "Poland",
      },
      {
        referenceCountryCode: "PT",
        isActive: true,
        bankCodeLabel: "Bank Code",
        swiftCodeLabel: "Swift Code",
        countryId: 61,
        countryName: "Portugal",
      },
      {
        referenceCountryCode: "QA",
        isActive: true,
        swiftCodeLabel: "Swift Code",
        countryId: 25,
        countryName: "Qatar",
      },
      {
        referenceCountryCode: "RO",
        isActive: true,
        bankCodeLabel: "Bank Code",
        swiftCodeLabel: "Swift Code",
        countryId: 63,
        countryName: "Romania",
      },
      {
        referenceCountryCode: "RE",
        isActive: true,
        bankCodeLabel: "Bank Code",
        swiftCodeLabel: "Swift Code",
        countryId: 62,
        countryName: "Réunion",
      },
      {
        referenceCountryCode: "BL",
        isActive: true,
        bankCodeLabel: "Bank Code",
        swiftCodeLabel: "Swift Code",
        countryId: 64,
        countryName: "Saint Barthélemy",
      },
      {
        referenceCountryCode: "MF",
        isActive: true,
        bankCodeLabel: "Bank Code",
        swiftCodeLabel: "Swift Code",
        countryId: 65,
        countryName: "Saint Martin",
      },
      {
        referenceCountryCode: "PM",
        isActive: true,
        bankCodeLabel: "Bank Code",
        swiftCodeLabel: "Swift Code",
        countryId: 66,
        countryName: "Saint Pierre and Miquelon",
      },
      {
        referenceCountryCode: "SM",
        isActive: true,
        bankCodeLabel: "Bank Code",
        swiftCodeLabel: "Swift Code",
        countryId: 67,
        countryName: "San Marino",
      },
      {
        referenceCountryCode: "ES",
        isActive: true,
        bankCodeLabel: "Bank Code",
        swiftCodeLabel: "Swift Code",
        countryId: 70,
        countryName: "Spain",
      },
      {
        referenceCountryCode: "LK",
        isActive: true,
        bankCodeLabel: "Bank Code",
        countryId: 1,
        countryName: "Sri Lanka",
      },
      {
        referenceCountryCode: "TH",
        isActive: true,
        bankCodeLabel: "IBAN",
        swiftCodeLabel: "Swift Code",
        countryId: 3,
        countryName: "Thailand",
      },
      {
        referenceCountryCode: "GB",
        isActive: true,
        bankCodeLabel: "Bank Code",
        swiftCodeLabel: "Swift Code",
        countryId: 4,
        countryName: "United Kingdom",
      },
      {
        referenceCountryCode: "US",
        isActive: true,
        bankCodeLabel: "Routing Number",
        swiftCodeLabel: "Swift Code",
        countryId: 6,
        countryName: "United States",
      },
      {
        referenceCountryCode: "FI",
        isActive: true,
        bankCodeLabel: "Bank Code",
        swiftCodeLabel: "Swift Code",
        countryId: 27,
        countryName: "Åland Islands",
      },
    ],
  },
  error: {},
};

export const currencyName = {
  response: {
    status: true,
    errorCode: 0,
    errorDescription: null,
    responseDto: [
      {
        agentTransferApprovedSendingCurrenciesId: 1,
        isActive: true,
        clientCurrencyId: 4,
        currencyId: 4,
        currencyName: "British Pound",
        currencyCode: "GBP",
      },
    ],
  },
};

export const agentReceivingCountriesType = {
  response: {
    status: true,
    errorCode: 0,
    errorDescription: null,
    responseDto: {
      referenceCountryCode: "IN",
      isActive: true,
      bankCodeLabel: "IFSC",
      swiftCodeLabel: "Swift Code",
      countryId: 2,
      countryName: "India",
    },
  },

  error: {},
};

export const agentBeneficiaryDetailsSave = {
  response: {
    status: true,
    errorCode: 0,
    errorDescription: null,
    responseDto: {
      id: 1925,
      msg: "Agent beneficiary details saved SuccessFully",
    },
  },

  error: {
    status: false,
    errorCode: 777,
    errorDescription: "Agent Firstname can't already persist.",
    responseDto: null,
  },
};

export const addBank = {
  response: {
    status: true,
    errorCode: 0,
    errorDescription: null,
    responseDto: "Bank Details Save Sucessfully",
  },
  error: {
    status: false,
    errorCode: 777,
    errorDescription:
      "Specified BankDetails  Can't save. Specified Bank Details already exist.",
    responseDto: null,
  },
};

export const beneficiaryList = {
  responseIndividual: {
    status: true,
    errorCode: 0,
    errorDescription: null,
    responseDto: {
      pageNumber: 1,
      pageSize: 10,
      totalRecords: 60,
      payload: [
        {
          agentBeneficiaryDetailsId: 1906,
          beneficiaryFullName: "Rasathuraiiii Premkumr",
          countryCode: "LKA",
          countryId: 1,
        },
        {
          agentBeneficiaryDetailsId: 1903,
          beneficiaryFullName: "dumamayyTwmmo summayaTwmlmmo",
          countryCode: "LKA",
          countryId: 1,
        },
        {
          agentBeneficiaryDetailsId: 1888,
          beneficiaryFullName: "check dummyaTwwo",
          countryCode: "LKA",
          countryId: 1,
        },
        {
          agentBeneficiaryDetailsId: 1823,
          beneficiaryFullName: "dummyannbmbTwwokk fdgjkhgjlgky",
          countryCode: "LKA",
          countryId: 1,
        },
        {
          agentBeneficiaryDetailsId: 1822,
          beneficiaryFullName: "dummyannbmbTwwokk fdgjkhgjlgky",
          countryCode: "LKA",
          countryId: 1,
        },
        {
          agentBeneficiaryDetailsId: 1818,
          beneficiaryFullName: "dumamyTwo summayTwo",
          countryCode: "LKA",
          countryId: 1,
        },
        {
          agentBeneficiaryDetailsId: 1815,
          beneficiaryFullName: "dummyannbmbTwwok dummyaTwwo",
          countryCode: "LKA",
          countryId: 1,
        },
        {
          agentBeneficiaryDetailsId: 1813,
          beneficiaryFullName: "TestFE dummyaTwwo",
          countryCode: "LKA",
          countryId: 1,
        },
        {
          agentBeneficiaryDetailsId: 1812,
          beneficiaryFullName: "dummyabbTwwok dummyaTwwo",
          countryCode: "LKA",
          countryId: 1,
        },
        {
          agentBeneficiaryDetailsId: 1811,
          beneficiaryFullName: "dummyaTwwok dummyaTwwo",
          countryCode: "LKA",
          countryId: 1,
        },
      ],
    },
  },
  responseCorporate: {
    status: true,
    errorCode: 0,
    errorDescription: null,
    responseDto: {
      pageNumber: 1,
      pageSize: 10,
      totalRecords: 30,
      payload: [
        {
          agentBeneficiaryDetailsId: 1900,
          beneficiaryFullName: "dummmnnyjhjTrwwo",
          countryCode: "LKA",
          countryId: 1,
        },
        {
          agentBeneficiaryDetailsId: 1899,
          beneficiaryFullName: "dummmnnyjjTrwwo",
          countryCode: "LKA",
          countryId: 1,
        },
        {
          agentBeneficiaryDetailsId: 1898,
          beneficiaryFullName: "newbeb",
          countryCode: "LKA",
          countryId: 1,
        },
      ],
    },
  },
  error: {
    status: false,
    errorCode: 779,
    errorDescription: "Unable to retrieve the beneficiary details.",
    responseDto: null,
  },
};

export const beneficiaryView = {
  response: {
    status: true,
    errorCode: 0,
    errorDescription: null,
    responseDto: [
      {
        beneficiaryFirstName: "Rasathuraiiii",
        beneficiaryLastName: "Premkumr",
        bankName: "York Banks",
        accountNumber: "34552621",
        branchName: "TestBrancehererdd",
        prefix: "+44",
        contactNumber: "123456789123",
        beneficiaryAddress: "9, 5/4 Rudra mw",
        isCorporate: false,
        countryCode: "LKA",
      },
    ],
  },

  error: {
    status: false,
    errorCode: 775,
    errorDescription: "Error retrieve beneficiary basic details by id.",
    responseDto: null,
  },
};
